public class lab3 {
    public static void main(String[] args) {

        Znayka znayka = new Znayka("Знайка ", "Знайкой ");
        Wind wind = new Wind("Ветер ");
        Top top = new Top("верхушка ");
        Rocket rocket = new Rocket("Ракета ");
        Flight flight = new Flight("отлет");
        ZnaykaMove zmove = new ZnaykaMove();
        RocketMove rmove = new RocketMove();
        WindMove wmove = new WindMove();
        TopMove tmove = new TopMove();
        FlyghtMove fmove = new FlyghtMove();
        OtherWords otherwords = new OtherWords();
        ComparisonSwich comparisonswich = new ComparisonSwich();
        AchieveSwitch achieveswitch =new AchieveSwitch();
        Comparison FirstComparison = Comparison.CIGAR;
        Comparison SecondComparison = Comparison.AIRSHIP;
        Achieve FirstAchieve = Achieve.STONE;
        Achieve SecondAchieve = Achieve.WEIGHTLESSNESS;
        Achieve ThirdAchieve = Achieve.SHIP;
        System.out.print(znayka.getName1());
        zmove.Wonder();
        otherwords.When();
        zmove.WokeUp();
        otherwords.SomeMorning();
        fmove.Assign();
        System.out.print(flight.getName());
        otherwords.OnMoon();
        zmove.nSee();
        otherwords.WindowRocket();
        System.out.println();
        otherwords.Usually();
        otherwords.When();
        System.out.print(znayka.getName1());
        zmove.Looking();
        otherwords.InWindow();
        zmove.See();
        otherwords.Rockety();
        System.out.print(top.getName());
        otherwords.Which();
        tmove.View();
        otherwords.InSky();
        comparisonswich.CSwith(FirstComparison);
        otherwords.Or();
        comparisonswich.CSwith(SecondComparison);
        System.out.println(znayka.getName1());
        zmove.Admiring();
        otherwords.BeautifulRocket();
        zmove.Dream();
        System.out.print(rocket.getName());
        rmove.Mole();
        otherwords.Before();
        System.out.print(znayka.getName2());
        rmove.Glitter();
        otherwords.SteelSide();
        System.out.println();
        System.out.print(wind.getName());
        wmove.Blow();
        otherwords.InFace();
        System.out.println();
        otherwords.FromThis();
        System.out.print(znayka.getName1());
        zmove.Peppy();
        System.out.println();
        otherwords.Moments();
        System.out.print(znayka.getName1());
        zmove.Sing();
        zmove.Scream();
        zmove.Opening();
        zmove.Fly();
        System.out.println();
        otherwords.TWhen();
        System.out.print(znayka.getName1());
        zmove.nSee();
        otherwords.Rockety();
        otherwords.Thats();
        zmove.Think();
        otherwords.Dream();
        achieveswitch.ASwitch(FirstAchieve);
        achieveswitch.ASwitch(SecondAchieve);
        achieveswitch.ASwitch(ThirdAchieve);
    }
}
